---
- name: Include DNS setup
  ansible.builtin.include_tasks: 01_dns.yml
  tags: [dns]

- name: Include Exit Node deployment
  ansible.builtin.include_tasks: 02_deploy.yml
  tags: [deploy, exit_node]
