---
- name: Include DNS setup
  ansible.builtin.include_tasks: 01_dns.yml
  tags: [dns]

- name: Include Entry Node deployment
  ansible.builtin.include_tasks: 02_deploy.yml
  tags: [deploy, entry_node]
