---
- name: Configure Cloudflare DNS
  ansible.builtin.include_tasks: 01_cloudflare.yml

- name: Generate SSL certificate
  ansible.builtin.include_tasks: 02_ssl.yml

- name: Deploy configuration files
  ansible.builtin.include_tasks: 03_configs.yml

- name: Deploy VPN stack
  ansible.builtin.include_tasks: 04_stack.yml
