---
- name: Restart containers
  community.docker.docker_compose_v2:
    project_src: "{{ vpn_path }}"
    state: present
    recreate: always

- name: Restart nginx
  community.docker.docker_compose_v2:
    project_src: "{{ vpn_path }}"
    services:
      - nginx
    state: present
    recreate: always

- name: Restart xui
  community.docker.docker_container:
    name: xui
    state: started
    restart: true
