---
- name: Add DigitalOcean GPG key
  ansible.builtin.get_url:
    url: https://repos.insights.digitalocean.com/sonar-agent.asc
    dest: /etc/apt/keyrings/digitalocean-agent.asc
    mode: "0644"

- name: Add DigitalOcean repository
  ansible.builtin.apt_repository:
    repo: deb [signed-by=/etc/apt/keyrings/digitalocean-agent.asc] https://repos.insights.digitalocean.com/apt/do-agent/ main main
    filename: digitalocean-agent
    state: present

- name: Install do-agent
  ansible.builtin.apt:
    name: do-agent
    state: present
    update_cache: true
