---
- name: Install common packages
  ansible.builtin.include_tasks: 01_packages.yml

- name: Configure sudo
  ansible.builtin.include_tasks: 02_sudo.yml

- name: Configure user accounts
  ansible.builtin.include_tasks: 03_accounts.yml

- name: Configure DNS
  ansible.builtin.include_tasks: 05_dns.yml

- name: Configure sysctl network tuning
  ansible.builtin.include_tasks: 06_sysctl.yml

- name: Configure firewall
  ansible.builtin.include_tasks: 04_firewall.yml

- name: Disable IPv6
  ansible.builtin.include_tasks: 07_disable_ipv6.yml
