---
- name: Install common packages
  ansible.builtin.include_tasks: 01_packages.yml

- name: Configure sudo
  ansible.builtin.include_tasks: 02_sudo.yml

- name: Configure user accounts
  ansible.builtin.include_tasks: 03_accounts.yml

- name: Configure firewall
  ansible.builtin.include_tasks: 04_firewall.yml

- name: Install DigitalOcean Metrics Agent
  ansible.builtin.include_tasks: 05_do_agent.yml
